version: '3.7'

services:
  ts-node:
    container_name: Node_Duettia
    image: node:16-alpine
    build: .
    ports:
      - 5173:5173
      - 24678:24678
    volumes:
      - ./:/home/node/app/
    working_dir: /home/node/app/
    command: sh -c "
      pnpm install &&
      pnpm run dev --host=0.0.0.0
      "
    depends_on:
      - pocketbase

  pocketbase:
    container_name: PocketBase_Duettia
    image: alpine:latest
    ports:
      - 8090:8090
    volumes:
      - ./:/home/pb/
    working_dir: /home/pb/
    command: sh -c "
      ./pocketbaseLinux serve --http=0.0.0.0:8090
      "
